on: push
name: Build and Generate Android Apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Building APK
        uses: ./action
        with:
          args: /r:True /t:SignAndroidPackage /p:AndroidSdkDirectory=/android/sdk HelloWorld/HelloWorld.Android/HelloWorld.Android.csproj
      - name: Artifacts
        run: mkdir -p /github/workspace/apks
        run: cp HelloWorld/HelloWorld.Android/bin/debug/*.apk /github/workspace/apks
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
          with:
            name: apks
            path: /github/workspace/apks
          
