on: push
name: Build and Generate Android Apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Building APK
        uses: ./action
        with:
          args: /r:True HelloWorld/HelloWorld/HelloWorld.csproj
          path: HelloWorld/HelloWorld/bin/Debug
          
