on: push
name: Build and Generate Android Apk
jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Building APK
        uses: ./action
        with:
          args: /t:SignAndroidPackage HelloWorld/HelloWorld/HelloWorld.csproj
      - name: Upload Artifacts
        uses: ./action
        with:
          name: Upload APK
          path: HelloWorld/HelloWorld/bin/Debug/*.apk
